# Site settings
title: Trash Panda Toolkit - Workflow as a Service (WaaS)
email: mail@tptoolkit.xyz
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tptoolkit.xyz/" # the base hostname & protocol for your site

twitter_username: vo3xel
github_username: vo3xel

# Build settings
markdown: kramdown
